name: macOS VNC

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-26

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure macOS VNC
        env:
          VNC_USER_PASSWORD: ${{ secrets.VNC_USER_PASSWORD }}
          VNC_PASSWORD: ${{ secrets.VNC_PASSWORD }}
        run: |
          chmod +x configure.sh
          ./configure.sh \
            "$VNC_USER_PASSWORD" \
            "$VNC_PASSWORD"

      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Show Tailscale information
        run: |
          echo "=== TAILSCALE STATUS ==="
          tailscale status

          echo
          echo "=== TAILSCALE IP ==="
          tailscale ip -4

          echo
          echo "=== VNC PORT ==="
          nc -zv 127.0.0.1 5900

      - name: Keep runner alive
        run: |
          echo "VNC is ready."
          echo
          echo "Connect using:"
          echo "Tailscale-IP:5900"
          echo
          while true; do
            sleep 60
          done
